[project]
name = "todo"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "waly-dsk", email = "davowilfried3@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx2>=0.28.0",
    "psycopg[binary]>=3.3.4",
    "ruff>=0.16.3",
    "uvicorn>=0.52.3",
]

[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "pytest>=9.1.1",
]
